### ISSUE TITLE
deploy snapshot to Maven Central

### ISSUE THREAD

**Issue by monperrus** [SpoonLabs/sonarqube-repair#76]
@fermadeiral you can access to the groupId on https://issues.sonatype.org/browse/OSSRH-53806

**Comment by fermadeiral** [comment]
I have signed up for a Jira account at https://issues.sonatype.org with the username "fermadeiral", which I believe to be the username you asked me yesterday. If I understood properly from the link you just mentioned, I need rights to deploy to "se.kth.castor". Are you going to request that for me or should I do it?

**Comment by monperrus** [comment]
> Are you going to request that for me or should I do it?

Go ahead, do the request, it's a good training!

**Comment by fermadeiral** [comment]
> Go ahead, do the request, it's a good training!

Request done. I will bring news when I have some.

**Comment by fermadeiral** [comment]
Permissions granted.

Also see: https://issues.sonatype.org/browse/OSSRH-56783

**Comment by fermadeiral** [comment]
We have a first snapshot deployed: https://oss.sonatype.org/content/repositories/snapshots/se/kth/castor/sonarqube-repair/

**Comment by monperrus** [comment]
hurray!
