### ISSUE TITLE
Remove sonarjava?

### ISSUE THREAD

**Issue by fermadeiral** [SpoonLabs/sonarqube-repair#97]
Hi everyone,

We started to have a lot of big problems since we started to use sonarjava (e.g., #94 and #96). Well, sonarjava is not meant to be used as we want, and right now I see no way to make things work with sonarjava. My suggestion: to remove sonarjava from the project.

However, we cannot switch back to how it was before (without sonarjava) easily, because there are processors that previously relied on sonar web API, and it was not nice at all to have incompatible processors. My second suggestion: 1) to remove the code-smell-related processors ([Unused assignments should be removed](https://rules.sonarsource.com/java/RSPEC-1854) and [Fields in a "Serializable" class should either be transient or serializable](https://rules.sonarsource.com/java/RSPEC-1948)), and 2) to work on the processor that is bug-related and previously used the sonar web API ([Resources should be closed](https://rules.sonarsource.com/java/RSPEC-2095)) to work without the sonar web API, I could do it myself.

We need a stable and focused ground. Processors only based on Spoon might be enough to us, and leaving code in the project that will not be used (which was the case of the processors using sonar web API) only complicates things too.

WDYT?

**Comment by henry-lp** [comment]
I agree. Currently I think the gain is too little in comparison to the loss by having sonarjava.

**Comment by fermadeiral** [comment]
The issue #96 was closed, but we still have the problem that @henry-lp discovered (#94).

**Comment by fermadeiral** [comment]
This issue can be closed because both mentioned issues were fixed.
